### ISSUE TITLE
Interesting idea

### ISSUE THREAD

**Issue by stavroskasidis** [ctrl-alt-d/BlazorServerTree#1]
Hey, what's up !

Responding to your email from earlier this week. 

This seems like a nice candidate for a component for blazor. However there is currently a limitation in Blazor that I think prevents you from creating a treelist or grid component like this: **No template support :(** 

Here are some issues tracking this here : 
https://github.com/aspnet/Blazor/issues/404
https://github.com/aspnet/Blazor/issues/1094 (community implementation, not merged)

Overlooking that limitation however, you could draw some inspiration from other similar frameworks/components like:
https://www.telerik.com/kendo-vue-ui/components/treelist/

This can give you an idea on how to move forward designing your component. 

First thing I would do is deciding on the shape of the API (i.e. the way the component is used by an other developer) and then starting implementing all the internal code to make it work.

**Comment by ctrl-alt-d** [comment]
Hi Mr @stavroskasidis,

Your advice and contribution are welcome!

Nice idea the `RenderFragment<T>` I hope will be included on new versions to rewrite the component more closed to the current kendo vue ui tree list component. Meantime I will isolate  `UITreeComponent` and test it on my own prototypes, to identify improvements.

Also, I see now that I have implemented a kind of [treelistdatasource](https://docs.telerik.com/kendo-ui/api/javascript/data/treelistdatasource), may be, we all have the same needs on control backend.

I would like to thank again you about to share [BlazorContextMenu](https://github.com/stavroskasidis/BlazorContextMenu) code, I have learned a lot there.

Best regards.
