### ISSUE TITLE
How to run the solution in VS2019+NET Core 3.1?

### ISSUE THREAD

**Issue by Oleg26Dev** [ctrl-alt-d/BlazorServerTree#3]
I open the solution in VS2019 but all 3 projects cannot be loaded.
Could you please fix the projects?

**Comment by ctrl-alt-d** [comment]
Hi @Oleg26Dev ,

this project is 2 years old Blazor project. It has a 'DEPRECTED' disclaimer. Is more easy to create a new one than to upgrade it. Thanks about your interest.
